import Link from "next/link";
import { ArrowRight, TriangleAlert } from "lucide-react";
import { EmptyState, MetricCard, ProgressBar, StatusBadge } from "@/components/design-system";
import type { StudentOverview } from "@/server/student/overview";

function resultMeta(state: string, passed: number, total: number) {
  if (state === "COMPILATION_ERROR") return { label: "Compilation error", tone: "compilation-error" as const };
  if (state !== "COMPLETED") return { label: state.replaceAll("_", " "), tone: "danger" as const };
  if (passed === total) return { label: "Passed all provided tests", tone: "passed" as const };
  return { label: `${passed}/${total} tests`, tone: "warning" as const };
}

function dateLabel(value: string | null) {
  return value ? new Date(value).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" }) : "No deadline";
}

function scoreLabel(score: number) {
  return `${score.toFixed(1)}/10`;
}

export function StudentDashboard({ overview }: { overview: StudentOverview }) {
  const active = overview.practicals.find((item) => !item.latestSubmission) ?? overview.practicals[0] ?? null;
  const attention = overview.practicals.find((item) => item.latestSubmission && item.latestSubmission.passedTests < item.latestSubmission.totalTests) ?? null;
  return <div className="space-y-6"><header><p className="eyebrow">Student workspace</p><h1 className="page-heading">Dashboard</h1><p className="page-subtitle">Continue your practical work and review your persisted attempts.</p></header>
    <div className="grid gap-4 xl:grid-cols-[0.8fr_1.7fr]">
      <section className="panel p-4"><div className="flex items-center gap-2"><TriangleAlert size={14} className={attention ? "text-amber-400" : "text-emerald-400"} /><p className="text-[10px] font-semibold uppercase tracking-wider text-[var(--text-muted)]">Needs attention</p></div>{attention ? <><h2 className="mt-4 text-sm font-semibold text-white">{attention.title}</h2><p className="mt-1 text-xs text-[var(--text-secondary)]">Latest attempt passed {attention.latestSubmission?.passedTests}/{attention.latestSubmission?.totalTests} provided tests.</p><Link href={`/tasks/${attention.id}`} className="button-secondary mt-4 w-full">Start next attempt <ArrowRight size={13} /></Link></> : <><h2 className="mt-4 text-sm font-semibold text-white">You are up to date</h2><p className="mt-1 text-xs text-[var(--text-secondary)]">No failed latest attempt needs attention.</p></>}</section>
      <section className="panel p-4">{active ? <><div className="flex items-start justify-between"><div><p className="eyebrow">Current practical</p><h2 className="mt-2 text-base font-semibold text-white">{active.title}</h2><p className="mt-1 text-xs text-[var(--text-muted)]">{active.classroom.subject} · {active.classroom.name}</p></div><StatusBadge tone={active.latestSubmission ? "success" : active.latestSession?.status === "ACTIVE" ? "warning" : "published"}>{active.latestSubmission ? "Submitted" : active.latestSession?.status === "ACTIVE" ? "In progress" : "Ready"}</StatusBadge></div><div className="mt-5 grid gap-3 border-t border-[var(--border)] pt-4 sm:grid-cols-3"><div><p className="text-[10px] uppercase text-[var(--text-muted)]">Visible tests</p><p className="mt-1 text-xs font-semibold text-white">{active.visibleTestCount}</p></div><div><p className="text-[10px] uppercase text-[var(--text-muted)]">Deadline</p><p className="mt-1 text-xs font-semibold text-white">{dateLabel(active.deadline)}</p></div><div className="sm:text-right"><Link href={`/tasks/${active.id}`} className="button">{active.latestSession?.status === "ACTIVE" ? "Continue coding" : active.latestSubmission ? "Start next attempt" : "Open practical"} <ArrowRight size={13} /></Link></div></div></> : <EmptyState title="No published practicals" description="Published work will appear here after you join a class." />}</section>
    </div>
    <div className="grid gap-5 xl:grid-cols-2"><section><div className="section-heading-row"><h2 className="section-heading">Your classes</h2><Link href="/classes" className="text-link">View all</Link></div>{overview.classes.length ? <div className="panel divide-y divide-[var(--border-subtle)]">{overview.classes.slice(0,4).map((item) => <Link href={`/classes/${item.id}`} key={item.id} className="block px-4 py-3 hover:bg-[var(--surface-hover)]"><div className="flex justify-between gap-4"><div><p className="text-xs font-semibold text-white">{item.name}</p><p className="mt-0.5 text-[11px] text-[var(--text-muted)]">{item.subject} · {item.practicalCount} practicals</p></div><span className="text-xs text-[var(--text-secondary)]">{item.completionPercentage}%</span></div><div className="mt-2"><ProgressBar value={item.completionPercentage} showPercentage={false} /></div></Link>)}</div> : <EmptyState title="No classes" description="Join a classroom to begin." />}</section>
      <section><div className="section-heading-row"><h2 className="section-heading">Recent submissions</h2><Link href="/submissions" className="text-link">View all</Link></div>{overview.submissions.length ? <div className="panel divide-y divide-[var(--border-subtle)]">{overview.submissions.slice(0,5).map((item) => {const meta=resultMeta(item.state,item.passedTests,item.totalTests); return <Link href={`/submissions/${item.id}`} key={item.id} className="flex items-center gap-3 px-4 py-3 hover:bg-[var(--surface-hover)]"><span className={`signal-dot ${meta.tone==="passed"?"signal-success":meta.tone==="compilation-error"?"signal-danger":"signal-warning"}`} /><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-white">{item.practical.title}</p><p className="text-[11px] text-[var(--text-muted)]">Attempt #{item.attemptNumber} · Suggested {scoreLabel(item.suggestedScore)}</p></div><div className="text-right"><StatusBadge tone={item.publishedReviewExists?"success":"neutral"}>{item.publishedReviewExists?"Feedback published":"Awaiting feedback"}</StatusBadge><p className="mt-1 text-[10px] text-[var(--text-muted)]">{new Date(item.submittedAt).toLocaleString("en-IN")}</p></div></Link>})}</div> : <EmptyState title="No submissions" description="Your immutable attempts will appear here." />}</section></div>
  </div>;
}

export function StudentPracticals({ overview }: { overview: StudentOverview }) {
  return <div className="space-y-5"><header><p className="eyebrow">Student workspace</p><h1 className="page-heading">Practicals</h1><p className="page-subtitle">Published practicals available through your active classroom memberships.</p></header>{overview.practicals.length ? <div className="panel overflow-hidden"><div className="overflow-x-auto"><table className="dense-table"><thead><tr><th>Practical</th><th>Class</th><th>Visible tests</th><th>Latest attempt</th><th>Deadline</th><th>Status</th><th></th></tr></thead><tbody>{overview.practicals.map((item)=>{const meta=item.latestSubmission?resultMeta(item.latestSubmission.state,item.latestSubmission.passedTests,item.latestSubmission.totalTests):null;return <tr key={item.id}><td className="min-w-52 font-semibold text-white">{item.title}</td><td><p className="text-xs">{item.classroom.name}</p><p className="text-[11px] text-[var(--text-muted)]">{item.classroom.subject}</p></td><td>{item.visibleTestCount}</td><td>{item.latestSubmission?`#${item.latestSubmission.attemptNumber} · ${item.latestSubmission.passedTests}/${item.latestSubmission.totalTests}`:"—"}</td><td className="min-w-36 text-xs text-[var(--text-secondary)]">{dateLabel(item.deadline)}</td><td><StatusBadge tone={meta?.tone ?? (item.latestSession?"warning":"published")}>{meta?.label ?? (item.latestSession?"In progress":"Ready")}</StatusBadge></td><td><Link href={`/practicals/${item.id}`} className="icon-button"><ArrowRight size={13}/></Link></td></tr>})}</tbody></table></div></div>:<EmptyState title="No published practicals" description="Your teacher has not published work for your classes yet."/>}</div>;
}

export function StudentSubmissions({ overview }: { overview: StudentOverview }) {
  const feedbackCount = overview.submissions.filter((item) => item.publishedReviewExists).length;
  return <div className="space-y-5"><header><p className="eyebrow">Student workspace</p><h1 className="page-heading">Submission history</h1><p className="page-subtitle">Every row is a read-only attempt. Suggested test scores are separate from teacher-awarded marks.</p></header><div className="panel flex flex-wrap items-center gap-3 p-3"><div><p className="text-xs font-semibold text-white">{overview.submissions.length} immutable attempts</p><p className="mt-0.5 text-[10px] text-[var(--text-muted)]">Newest first · Simulated execution results</p></div><div className="ml-auto flex items-center gap-2"><StatusBadge tone={feedbackCount?"success":"neutral"}>{feedbackCount} feedback published</StatusBadge></div></div>{overview.submissions.length?<div className="panel overflow-hidden"><div className="overflow-x-auto"><table className="dense-table"><thead><tr><th>Practical</th><th>Attempt</th><th>Test breakdown</th><th>Suggested score</th><th>Teacher feedback</th><th>Submitted</th><th></th></tr></thead><tbody>{overview.submissions.map((item)=>{const meta=resultMeta(item.state,item.passedTests,item.totalTests);return <tr key={item.id}><td className="min-w-52"><p className="font-semibold text-white">{item.practical.title}</p><p className="text-[11px] text-[var(--text-muted)]">{item.classroom.name} · {item.language==="CPP"?"C++":"Java"}</p></td><td>#{item.attemptNumber}</td><td className="min-w-40"><StatusBadge tone={meta.tone}>{meta.label}</StatusBadge><p className="mt-1 text-[10px] text-[var(--text-muted)]">Visible {item.visiblePassedTests}/{item.visibleTotalTests} · Hidden {item.hiddenPassedTests}/{item.hiddenTotalTests}</p></td><td><p className="font-semibold text-white">{scoreLabel(item.suggestedScore)}</p><p className="text-[10px] text-[var(--text-muted)]">Test-derived</p></td><td><StatusBadge tone={item.publishedReviewExists?"success":"neutral"}>{item.publishedReviewExists?"Published":"Not published"}</StatusBadge></td><td className="min-w-44 text-xs text-[var(--text-secondary)]">{new Date(item.submittedAt).toLocaleString("en-IN")}</td><td><Link href={`/submissions/${item.id}`} aria-label={`View attempt ${item.attemptNumber}`} className="icon-button"><ArrowRight size={13}/></Link></td></tr>})}</tbody></table></div></div>:<EmptyState title="No submissions yet" description="Run and submit a solution from a published practical."/>}</div>;
}

export function StudentProgress({ overview }: { overview: StudentOverview }) {
  return <div className="space-y-5"><header><p className="eyebrow">Student workspace</p><h1 className="page-heading">Progress</h1><p className="page-subtitle">Completion is based on practicals with at least one immutable submission.</p></header><section className="grid gap-3 sm:grid-cols-3"><MetricCard label="Published practicals" value={overview.summary.practicalCount}/><MetricCard label="Submitted practicals" value={overview.summary.submittedPracticalCount}/><MetricCard label="Overall completion" value={`${overview.summary.completionPercentage}%`}/></section><section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="section-heading">Class progress</h2><p className="section-description">Resubmissions do not inflate completion.</p></div></div>{overview.classes.length?<div className="divide-y divide-[var(--border-subtle)]">{overview.classes.map((item)=><Link href={`/classes/${item.id}`} key={item.id} className="grid items-center gap-4 px-4 py-4 hover:bg-[var(--surface-hover)] sm:grid-cols-[1fr_auto_minmax(180px,0.6fr)]"><div><p className="text-sm font-semibold text-white">{item.name}</p><p className="text-[11px] text-[var(--text-muted)]">{item.subject} · {item.section}</p></div><span className="text-xs text-[var(--text-secondary)]">{item.submittedPracticalCount}/{item.practicalCount} submitted</span><ProgressBar value={item.completionPercentage}/></Link>)}</div>:<div className="p-4"><EmptyState title="No class progress" description="Join a classroom to begin."/></div>}</section></div>;
}
