import Link from "next/link";
import { ArrowRight, TriangleAlert } from "lucide-react";
import { DemoShell } from "@/components/app-shell";
import { EmptyState, MetricCard, ProgressBar, StatusBadge } from "@/components/design-system";
import { resolveCurrentActorForPage } from "@/server/actors/page-actor";
import { getTeacherOverview } from "@/server/teacher/overview";
import { getStudentOverview } from "@/server/student/overview";
import { StudentProgress } from "@/features/student/student-pages";

export default async function TeacherProgressPage() {
  const actor = await resolveCurrentActorForPage({ demoActor: "teacher" });
  if (actor.role === "STUDENT") {
    const overview = await getStudentOverview(actor.id);
    return <DemoShell actor={actor}><StudentProgress overview={overview} /></DemoShell>;
  }
  const overview = await getTeacherOverview(actor.id);
  const published = overview.practicals.filter((item) => item.status === "PUBLISHED");
  const challenging = [...published].sort((a, b) => a.completionPercentage - b.completionPercentage).slice(0, 4);

  return <DemoShell actor={actor}><div className="space-y-5">
    <header><p className="eyebrow">Teacher workspace</p><h1 className="page-heading">Progress</h1><p className="page-subtitle">Deterministic completion based on active memberships and immutable submission attempts.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Students" value={overview.progress.eligibleStudentCount} detail="Distinct active memberships" /><MetricCard label="Overall completion" value={`${overview.progress.overallCompletionPercentage}%`} detail="Distinct student/practical pairs" /><MetricCard label="Completed pairs" value={`${overview.progress.completedStudentPracticalPairs}/${overview.progress.totalStudentPracticalPairs}`} detail="Resubmissions count once" /><MetricCard label="Needs attention" value={overview.attention.length} detail="Objective signals only" /></section>

    <div className="grid gap-5 xl:grid-cols-[1.6fr_0.9fr]">
      <div className="space-y-5">
        <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="section-heading">Practical progress</h2><p className="section-description">Published practical completion across active students.</p></div><span className="count-chip">{published.length}</span></div>{published.length ? <div className="overflow-x-auto"><table className="dense-table"><thead><tr><th>Practical</th><th>Class</th><th>Submitted</th><th>Completion</th><th>Deadline</th><th></th></tr></thead><tbody>{published.map((practical) => <tr key={practical.id}><td className="min-w-48 font-semibold text-white">{practical.title}</td><td className="min-w-40"><p className="text-xs">{practical.classroomName}</p><p className="text-[11px] text-[var(--text-muted)]">{practical.classroomSubject}</p></td><td>{practical.submittedCount}/{practical.studentCount}</td><td className="min-w-44"><ProgressBar value={practical.completionPercentage} /></td><td className="text-xs text-[var(--text-secondary)]">{practical.deadline ? new Date(practical.deadline).toLocaleDateString("en-IN") : "No deadline"}</td><td><Link href={`/classes/${practical.classroomId}/students`} className="icon-button"><ArrowRight size={13} /></Link></td></tr>)}</tbody></table></div> : <div className="p-4"><EmptyState title="No published practicals" description="Progress appears after a practical is published." /></div>}</section>
        <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="section-heading">Student progress</h2><p className="section-description">Completion across practicals available through active memberships.</p></div><span className="count-chip">{overview.progress.students.length}</span></div>{overview.progress.students.length ? <div className="overflow-x-auto"><table className="dense-table"><thead><tr><th>Student</th><th>Submitted practicals</th><th>Completion</th><th>Latest submission</th><th>Status</th></tr></thead><tbody>{overview.progress.students.map((student) => <tr key={student.id}><td className="min-w-48"><p className="font-semibold text-white">{student.name}</p><p className="text-[11px] text-[var(--text-muted)]">{student.email}</p></td><td>{student.submittedPracticalCount}/{student.availablePracticalCount}</td><td className="min-w-44"><ProgressBar value={student.completionPercentage} /></td><td className="min-w-40 text-xs text-[var(--text-secondary)]">{student.latestActivityAt ? new Date(student.latestActivityAt).toLocaleString("en-IN") : "No submission"}</td><td><StatusBadge tone={student.availablePracticalCount > 0 && student.completionPercentage === 100 ? "success" : student.submittedPracticalCount > 0 ? "warning" : "neutral"}>{student.availablePracticalCount === 0 ? "No published work" : student.completionPercentage === 100 ? "Complete" : student.submittedPracticalCount > 0 ? "In progress" : "Not started"}</StatusBadge></td></tr>)}</tbody></table></div> : <div className="p-4"><EmptyState title="No students" description="Active student memberships will appear here." /></div>}</section>
      </div>
      <aside className="space-y-5">
        <section className="panel overflow-hidden"><div className="panel-header"><div className="flex items-center gap-2"><TriangleAlert size={14} className="text-amber-400" /><h2 className="section-heading">Needs attention</h2></div><span className="count-chip">{overview.attention.length}</span></div>{overview.attention.length ? <div className="divide-y divide-[var(--border-subtle)]">{overview.attention.map((item) => <Link href={item.href} key={item.id} className="block px-4 py-3 hover:bg-[var(--surface-hover)]"><div className="flex items-start gap-2"><span className={`signal-dot signal-${item.tone} mt-1`} /><div><p className="text-xs font-semibold text-white">{item.title}</p><p className="mt-1 text-[11px] leading-4 text-[var(--text-muted)]">{item.detail}</p></div></div></Link>)}</div> : <div className="p-4"><EmptyState title="No attention signals" description="No measurable completion or deadline signal needs review." /></div>}</section>
        <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="section-heading">Lowest completion</h2><p className="section-description">Practical-level facts, not student risk scores.</p></div></div>{challenging.length ? <div className="divide-y divide-[var(--border-subtle)]">{challenging.map((item) => <Link href={`/classes/${item.classroomId}/students`} key={item.id} className="block px-4 py-3 hover:bg-[var(--surface-hover)]"><div className="flex justify-between gap-3"><p className="text-xs font-semibold text-white">{item.title}</p><span className="text-xs text-[var(--text-secondary)]">{item.completionPercentage}%</span></div><p className="mt-1 text-[11px] text-[var(--text-muted)]">{item.classroomName} · {item.submittedCount}/{item.studentCount} submitted</p><div className="mt-2"><ProgressBar value={item.completionPercentage} showPercentage={false} /></div></Link>)}</div> : <div className="p-4"><EmptyState title="No completion data" description="Published practicals will appear here." /></div>}</section>
      </aside>
    </div>
  </div></DemoShell>;
}
