import type { Classroom, MembershipRole, Task } from "@prisma/client";
import { getClassrooms } from "@/data/classroom-repository";

export type ClassroomCardViewModel = { id: string; name: string; subject: string; section: string; studentCount: number; activePracticalCount: number; nearestDeadline: string | null; joinCode: string; status: "ACTIVE" | "ARCHIVED"; latestPractical: { title: string; submittedCount: number; pendingCount: number; completionPercentage: number } | null };
export type MyClassesViewModel = { summary: { activeClassCount: number; totalStudentCount: number; practicalsDueSoon: number }; activeClasses: ClassroomCardViewModel[]; archivedClasses: ClassroomCardViewModel[] };
type DbClassroom = Classroom & { memberships: { role: MembershipRole }[]; tasks: Task[] };

function toCard(classroom: DbClassroom): ClassroomCardViewModel { const students = classroom.memberships.filter((membership) => membership.role === "STUDENT").length; const latest = classroom.tasks.find((task) => task.status === "PUBLISHED") ?? null; return { id: classroom.id, name: classroom.name, subject: classroom.subject, section: classroom.section, studentCount: students, activePracticalCount: classroom.tasks.filter((task) => task.status === "PUBLISHED").length, nearestDeadline: latest?.deadline?.toISOString() ?? null, joinCode: classroom.joinCode, status: "ACTIVE", latestPractical: latest ? { title: latest.title, submittedCount: 0, pendingCount: students, completionPercentage: 0 } : null }; }
export async function getMyClassesViewModel(): Promise<MyClassesViewModel> { const activeClasses = (await getClassrooms()).map(toCard); const dueSoon = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); return { summary: { activeClassCount: activeClasses.length, totalStudentCount: activeClasses.reduce((total, item) => total + item.studentCount, 0), practicalsDueSoon: activeClasses.filter((item) => item.nearestDeadline && new Date(item.nearestDeadline) <= dueSoon).length }, activeClasses, archivedClasses: [] }; }
