import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Clock3, TriangleAlert } from "lucide-react";
import { DemoShell } from "@/components/app-shell";
import { EmptyState, StatusBadge } from "@/components/design-system";
import { resolveCurrentActorForPage } from "@/server/actors/page-actor";
import { getStudentPractical } from "@/server/student/overview";

export default async function StudentPracticalPage({ params }: { params: Promise<{ taskId: string }> }) {
  const { taskId } = await params;
  const actor = await resolveCurrentActorForPage({ demoActor: "student", requiredRole: "STUDENT" });
  const practical = await getStudentPractical(actor.id, taskId);
  if (!practical) notFound();
  const latest = practical.latestSubmission;
  const needsAttention = latest && latest.passedTests < latest.totalTests;
  return <DemoShell actor={actor}><div className="space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><nav className="mb-3 flex gap-2 text-xs text-[var(--text-muted)]"><Link href="/classes" className="hover:text-white">Classes</Link><span>/</span><Link href={`/classes/${practical.classroom.id}`} className="hover:text-white">{practical.classroom.name}</Link><span>/</span><span>{practical.title}</span></nav><p className="eyebrow">Published practical</p><h1 className="page-heading">{practical.title}</h1><p className="page-subtitle">{practical.classroom.subject} · {practical.classroom.name}</p></div><Link href={`/tasks/${practical.id}`} className="button">{practical.latestSession ? "Continue coding" : "Start coding"} <ArrowRight size={13}/></Link></header>
    <section className="panel grid gap-4 p-4 sm:grid-cols-4"><div><p className="text-[10px] uppercase text-[var(--text-muted)]">Status</p><div className="mt-2"><StatusBadge tone={latest?"success":practical.latestSession?"warning":"published"}>{latest?"Submitted":practical.latestSession?"In progress":"Ready"}</StatusBadge></div></div><div><p className="text-[10px] uppercase text-[var(--text-muted)]">Visible tests</p><p className="mt-2 text-sm font-semibold text-white">{practical.visibleTestCount}</p></div><div><p className="text-[10px] uppercase text-[var(--text-muted)]">Attempts</p><p className="mt-2 text-sm font-semibold text-white">{practical.attempts.length}</p></div><div><p className="text-[10px] uppercase text-[var(--text-muted)]">Deadline</p><p className="mt-2 text-xs font-semibold text-white"><Clock3 size={12} className="mr-1 inline"/>{practical.deadline?new Date(practical.deadline).toLocaleString("en-IN"):"No deadline"}</p></div></section>
    <div className="grid gap-5 xl:grid-cols-[1.5fr_0.8fr]"><main className="space-y-5"><section className="panel p-5"><h2 className="section-heading">Instructions</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[var(--text-secondary)]">{practical.instructions}</p>{practical.constraints?<><h3 className="mt-5 text-xs font-semibold uppercase tracking-wider text-[var(--text-muted)]">Constraints</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[var(--text-secondary)]">{practical.constraints}</p></>:null}</section>{needsAttention?<section className="flex items-center gap-3 rounded-[var(--radius)] border border-amber-500/25 bg-amber-500/5 p-4"><TriangleAlert size={16} className="text-amber-400"/><div className="flex-1"><p className="text-xs font-semibold text-white">Latest attempt needs another look</p><p className="mt-1 text-[11px] text-[var(--text-muted)]">{latest.passedTests}/{latest.totalTests} provided tests passed.</p></div><Link href={`/tasks/${practical.id}`} className="button-secondary">Fix submission <ArrowRight size={12}/></Link></section>:null}</main><aside className="panel self-start overflow-hidden"><div className="panel-header"><div><h2 className="section-heading">Submission history</h2><p className="section-description">Immutable attempts</p></div><span className="count-chip">{practical.attempts.length}</span></div>{practical.attempts.length?<div className="divide-y divide-[var(--border-subtle)]">{practical.attempts.map((attempt)=><Link href={`/submissions/${attempt.id}`} key={attempt.id} className="block px-4 py-3 hover:bg-[var(--surface-hover)]"><div className="flex justify-between gap-3"><p className="text-xs font-semibold text-white">Attempt #{attempt.attemptNumber}</p><span className="text-xs text-[var(--text-secondary)]">{attempt.passedTests}/{attempt.totalTests}</span></div><p className="mt-1 text-[10px] text-[var(--text-muted)]">{new Date(attempt.submittedAt).toLocaleString("en-IN")} · {attempt.language}</p></Link>)}</div>:<div className="p-4"><EmptyState title="No submissions" description="Your attempts will appear here after submission."/></div>}</aside></div>
  </div></DemoShell>;
}
