CREATE TYPE "PlatformRole" AS ENUM ('TEACHER', 'STUDENT');
CREATE TYPE "ClassroomStatus" AS ENUM ('ACTIVE', 'ARCHIVED');
CREATE TYPE "MembershipRole" AS ENUM ('TEACHER', 'STUDENT');
CREATE TYPE "TaskStatus" AS ENUM ('DRAFT', 'PUBLISHED');
CREATE TYPE "AllowedLanguage" AS ENUM ('CPP', 'JAVA');
CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "platformRole" "PlatformRole" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Classroom" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "subject" TEXT NOT NULL, "section" TEXT NOT NULL, "ownerTeacherId" TEXT NOT NULL, "joinCode" TEXT NOT NULL, "status" "ClassroomStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Classroom_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ClassMembership" ("id" TEXT NOT NULL, "classroomId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" "MembershipRole" NOT NULL, "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "active" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "ClassMembership_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Task" ("id" TEXT NOT NULL, "classroomId" TEXT NOT NULL, "authorTeacherId" TEXT NOT NULL, "title" TEXT NOT NULL, "instructions" TEXT NOT NULL, "constraints" TEXT, "allowedLanguages" "AllowedLanguage"[], "status" "TaskStatus" NOT NULL DEFAULT 'DRAFT', "deadline" TIMESTAMP(3), "publishedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Task_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TestCase" ("id" TEXT NOT NULL, "taskId" TEXT NOT NULL, "position" INTEGER NOT NULL, "input" TEXT NOT NULL, "expectedOutput" TEXT NOT NULL, "visible" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TestCase_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Classroom_joinCode_key" ON "Classroom"("joinCode");
CREATE UNIQUE INDEX "ClassMembership_classroomId_userId_key" ON "ClassMembership"("classroomId", "userId");
CREATE UNIQUE INDEX "TestCase_taskId_position_key" ON "TestCase"("taskId", "position");
ALTER TABLE "Classroom" ADD CONSTRAINT "Classroom_ownerTeacherId_fkey" FOREIGN KEY ("ownerTeacherId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ClassMembership" ADD CONSTRAINT "ClassMembership_classroomId_fkey" FOREIGN KEY ("classroomId") REFERENCES "Classroom"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassMembership" ADD CONSTRAINT "ClassMembership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_classroomId_fkey" FOREIGN KEY ("classroomId") REFERENCES "Classroom"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_authorTeacherId_fkey" FOREIGN KEY ("authorTeacherId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TestCase" ADD CONSTRAINT "TestCase_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;
